### ISSUE TITLE
[Remoto] Desenvolvedor React front-end Junior - @vagasprajr

### ISSUE THREAD

**Issue by vagasprajr** [vagasprajr/vagas#1]
## Nossa empresa

@vagasprajr é um bot que busca vagas para júnior; iniciantes; estágios; trainees na internet e posta no Twitter; Telegram; Blue Sky; Facebook e em nosso site: https://vagasprajr.com.br/

## Descrição da vaga

Buscamos 1 profissional iniciante com no mínimo 1 ano de experiência como frontend React para atuar como freelance.

**### Isso é uma vaga para prestador de serviços freelance**.

Trabalhe a hora que quiser e negocie o tempo que precisar para entregar as tarefas. 

Os pagamentos serão efetuados por tarefas completas em produção.

- 30% com o primeiro pull request aprovado para code review e o restante na entrega em produção.
- O profissional deve oferecer ao menos 3 meses de garantia para eventuais bugs e correções.

A principal tarefa do desenvolvedor será deixar a UI/UX mais bonita e funcional do site: 

- https://vagasparajr.com/

e ajudar na criação de novas funcionalidades. Baseado no desempenho e resultados mais tarefas poderão ser entregues para o prestador de serviço.

## Local

Remoto

## Requisitos

Experiência mínima de 1 anos usando:

- Github
- React
- Testes unitários
- CSS; HTML; Tailwind

## Soft Skills

- Ser acessível e saber se comunicar;
- Não ter vergonha ou medo de perguntar;
- Se tiver algum problema que impeça de continuar a tarefa, avisar o mais rápido possível para receber mais informações ou ajuda para concluir o trabalho. Geralmente quando isso acontece é porque você não entendeu ou falta alguma informação, por tanto não tenha vergonha ou medo de perguntar nada. Não existe perguntas idiota.
- Sugerir melhorias e contribuir com novas idéias

## Benefícios

Envie o valor de sua hora de trabalho.

## Contratação

PJ

## Como se candidatar

Envie seu portfolio e currículo para: [vagasprajr@gmail.com](mailto:vagasprajr@gmail.com)

### Nível

- Júnior

### Regime

- PJ
- Freelance

### Alocação
- Remoto

### Previsão de início:
19 de fevereiro de 2024

**Comment by gustavokozlowski** [comment]
Enviado, vidnha!

**Comment by vagasprajr** [comment]
Infelizmente não estamos mais recebendo novas aplicações.
